getvideo.php
Add meta tag with codepage utf8 to getvideo.php
=> Fix: non-latin video title unreadable

getvideo.php
Fix VideoId Regex to support HTTP beside HTTPS
=> Fix Video Id Regex

config.php, curl.php, download.php, getimage.php, getvideo.php, index.php, ytdl.user.js
I've kept the work of @roukmoute and resolve the conflicts.
refs #162
=> Coding style

getvideo.php, src/YoutubeDownloader.php
What changed:
- get_size(): disable `VerifyPeer `and enable `FollowRedirect` so we can get the video size
- getvideo.php: increase page width and fix output result
=> Adding more video result and some information

getvideo.php, src/YoutubeDownloader.php
There is changed 2 things:
1. In getvideo.php wasn't used existing function for getting video ID
2. Function validateVideoId can be more effective and simplified in just few lines.
Function validateVideoId is tested with these URLs:
- http://youtu.be/dQw4w9WgXcQ
- http://www.youtube.com/embed/dQw4w9WgXcQ
- http://www.youtube.com/watch?v=dQw4w9WgXcQ
- http://www.youtube.com/?v=dQw4w9WgXcQ
- http://www.youtube.com/v/dQw4w9WgXcQ
- http://www.youtube.com/e/dQw4w9WgXcQ
- http://www.youtube.com/user/username#p/u/11/dQw4w9WgXcQ
- http://www.youtube.com/sandalsResorts#p/c/54B8C800269D7C1B/0/dQw4w9WgXcQ
- http://www.youtube.com/watch?feature=player_embedded&v=dQw4w9WgXcQ
- http://www.youtube.com/?feature=player_embedded&v=dQw4w9WgXcQ
- http://www.youtube.com/v/dQw4w9WgXcQ?fs=1&hl=en_US
- …
=> New Video ID validation logic in validateVideoId()

.gitignore, .travis.yml, composer.json, phpunit.xml.dist, src/YoutubeDownloader.php, tests/YoutubeDownloaderTest.php
As announced in #182 and #185 this is the next step to this goals:
- :package: Allow reusability in other projects
- :white_check_mark: Create unit tests
- :construction_worker: Add CI build system (Travis)
- :art: Keep the old UI (index.php, getvideo.php, config.php, etc.) for BC
This PR adds first unit tests and allows automated testing with [Travis CI](https://travis-ci.org). ![](https://api.travis-ci.org/Art4/YouTube-Downloader.svg)
Thanks to the new `composer.json` it is easy possible to use this project as a library in other projects.
I would be glad if this PR would be merged. :blush:
=> Introducing unit tests

css/custom.css, index.php, src/YoutubeDownloader.php
List of all updates:
- Fixed errors for Live streaming videos
- CSS is now in separate file 'css/custom.css'
- Some videos doesn't have both stream maps what we are looking for
=> Minor improvements and func updates

src/VideoInfo.php, tests/Unit/VideoInfoTest.php
https://github.com/jeckman/YouTube-Downloader/pull/195#issuecomment-306386320
=> fix phpunit tests

README.md
I've setted up thegoals from #191. Can someone please confirm the spelling and syntax? English is not my native language. 🙂
=> Add goals to README.md

src/SignatureDecipher.php
Beautify the script and fixing a logic error..
=> Use switch case and fix some code

common.php, composer.json, download.php, getimage.php, getvideo.php, index.php, src/Template/Engine.php, src/Template/Template.php, templates/error.php, templates/getvideo.php, templates/index.php, tests/Fixture/TestCase.php, tests/Unit/Template/EngineTest.php, tests/Unit/Template/TemplateTest.php
I've created a simple template engine that allows us to separate the HTML into template files.
=> Introducing template engine

.gitignore, composer.json, src/Stream.php, src/StreamMap.php, tests/Unit/StreamTest.php
I moved the stream parsing into a separate `Stream` class. The idea is that we create a `YoutubeVideo` from a youtube url and can get all available `Stream`s from that class. A `Stream` class will have all needed attributes for downloading the video like mime type, video_id, url (with deciphered signatur) and size.
=> Indroducing Stream class

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
I've created a contributing guideline with templates for issues and pull requests. I've also updated the README with details about installation, upgrading and contributing.
=> Add CONTRIBUTING and github templates, update README

templates/header.php
=> Update header.php Viewport for mobile

CHANGELOG.md, config/default.php, src/Application/ControllerAbstract.php, src/Application/DownloadController.php, src/Application/ImageController.php, src/Application/MainController.php, src/Application/ResultController.php, src/Provider/Youtube/Provider.php, src/Provider/Youtube/VideoInfo.php, src/ServiceProvider.php, src/Toolkit.php, src/VideoInfo/VideoInfo.php, tests/Unit/Application/ImageControllerTest.php, tests/Unit/Provider/Youtube/ProviderTest.php, tests/Unit/Provider/Youtube/VideoInfoTest.php
This PR refactores the Youtube Provider and moves more code from Toolkit.php into the controller. It also improves the mp3 downloader: I changed the dependency from aria2 to curl because we are already depending on curl. There is no need for aria2 for simply download a file.
This PR also fixes some bugs in the mp3 downloader. There are 2 maybe critical bugs that could allow an attacker to inject a CLI command through the query string.
=> Refactoring of Youtube provider and Controller

src/Provider/Youtube/VideoInfo.php, tests/Unit/Provider/Youtube/VideoInfoTest.php
=>  VideoInfo now contains video duration information

src/Provider/Youtube/SignatureDecipher.php
=> Fix https://github.com/jeckman/YouTube-Downloader/issues/322

src/Provider/Youtube/SignatureDecipher.php
To find the name of the signature function used regular expressions from [rg3/youtube-dl](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1189).
This PR fixes #341
=> Fix empty signature function

src/Provider/Youtube/SignatureDecipher.php
=> sometimes there are only two

src/Provider/Youtube/VideoInfo.php, tests/Unit/Provider/Youtube/VideoInfoTest.php
Ok,,, Now updated the Tests folder too.
=>  Enhance GetCleanedTitle()

config/default.php
For MP3 conversion. I'm not sure if most people will know this so I thought it would be good to include
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jeckman/youtube-downloader/354)
=> Document FFMPEG usage on Linux

src/Provider/Youtube/Provider.php
=> switching to https

src/Application/DownloadController.php
=> add config option for delete or no the cache file copy

config/default.php
=> update config file

templates/getvideo.php
=> rewrite full PHP and add option retry to load

templates/index.php
Can change the language and name of the button
=> Fix if we want change the button download name
